### ISSUE TITLE
Census - Automatic deploy on heroku

### ISSUE THREAD

**Issue by Dobloq** [pablotabares/decide#135]
By now project is deploy via cmd to heroku, it's intended to do it automatically after pass all tests in travis

**Comment by Dobloq** [comment]
Heroku gives the following error:

`-----> Python app detected
-----> Installing requirements with pip
-----> $ python decide/manage.py collectstatic --noinput
       Traceback (most recent call last):
         File "decide/manage.py", line 15, in <module>
           execute_from_command_line(sys.argv)
         File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
           utility.execute()
         File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 365, in execute
           self.fetch_command(subcommand).run_from_argv(self.argv)
         File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
           self.execute(*args, **cmd_options)
         File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/base.py", line 335, in execute
           output = self.handle(*args, **options)
         File "/app/.heroku/python/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 189, in handle
           collected = self.collect()
         File "/app/.heroku/python/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 105, in collect
           for path, storage in finder.list(self.ignore_patterns):
         File "/app/.heroku/python/lib/python3.7/site-packages/django/contrib/staticfiles/finders.py", line 125, in list
           for path in utils.get_files(storage, ignore_patterns):
         File "/app/.heroku/python/lib/python3.7/site-packages/django/contrib/staticfiles/utils.py", line 28, in get_files
           directories, files = storage.listdir(location)
         File "/app/.heroku/python/lib/python3.7/site-packages/django/core/files/storage.py", line 313, in listdir
           for entry in os.listdir(path):
       FileNotFoundError: [Errno 2] No such file or directory: '/tmp/build_27a8907c472aeb84e9998bde1ea5b8d8/decide/static'
 !     Error while running '$ python decide/manage.py collectstatic --noinput'.
       See traceback above for details.
       You may need to update application code to resolve this error.
       Or, you can disable collectstatic for this application:
          $ heroku config:set DISABLE_COLLECTSTATIC=1
       https://devcenter.heroku.com/articles/django-assets
 !     Push rejected, failed to compile Python app.
 !     Push failed
`
